version: "3.7"
services:
  dbserver:
    image: postgres:11-alpine
    container_name: apsso-dbserver
    environment:
      POSTGRES_USER: apsso-dbuser
      POSTGRES_PASSWORD: apsso-dbpasswd
      POSTGRES_DB: apsso-dbname
    volumes:
      - apsso-pgdata:/var/lib/postgresql/data
    ports:
      - "50000:5432"
  webapp:
    image: registry.gitlab.com/andrepenteado/ap-sso
    container_name: apsso-webapp
    ports:
      - "30000:8080"
    extra_hosts:
      - "host:127.0.0.1"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
volumes:
  apsso-pgdata:
