version: "3.7"
services:
  apsso-dbserver:
    image: postgres:11-alpine
    container_name: apsso-dbserver-container
    environment:
      POSTGRES_USER: apsso-dbuser
      POSTGRES_PASSWORD: apsso-dbpasswd
      POSTGRES_DB: apsso-dbname
    volumes:
      - apsso-pgdata:/var/lib/postgresql/data
    ports:
      - "50000:5432"
volumes:
  apsso-pgdata: